name: Frama-C-Eva-SARIF

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  run_eva:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Frama-C/Eva
      id: eva
      uses: frama-c/github-action-eva-sarif@v2
      with:
        eva-target: 'monocypher.eva'
    - name: Alarm count
      run: echo "Eva reported ${{ steps.eva.outputs.alarm-count }} alarm(s)"
    - name: Eva coverage estimation
      run: echo "Eva coverage estimation:${{ steps.eva.outputs.coverage }}"
    - uses: actions/upload-artifact@v2
      with:
        name: monocypher.sarif
        path: ${{ github.workspace }}/.frama-c/monocypher.sarif
